#!/usr/bin/env nu

export-env {
    # Use mise's root when present, else the git toplevel.
    $env.ROOT = ($env.MISE_PROJECT_ROOT? | default (^git rev-parse --show-toplevel | str trim))
    $env.SCRATCH_DIR = ($env.ROOT | path join .scratch)
    mkdir $env.SCRATCH_DIR
}

# Create a working/log directory for one test run, grouped under .scratch/runs
# and prefixed with a sortable timestamp so runs list in chronological order
# (newest last). Maintains a `latest-<target>` symlink and prunes all but the
# newest few runs per target. Returns the new directory path.
export def new-run-dir [target: string]: nothing -> string {
    let runs = ($env.SCRATCH_DIR | path join runs)
    mkdir $runs

    let stamp = (date now | format date '%Y%m%d-%H%M%S')
    let dir = (^mktemp -d ($runs | path join $"($stamp)-($target)-XXXX") | str trim)

    # Templates only — Caddyfile is written by write-test-caddyfile (ephemeral
    # port, per-run admin, no identity rewrite). Root Caddyfile stays for
    # local `mise start` / browser use on :8080 with fixed "dev" identity.
    ^cp -r ($env.ROOT | path join templates) $dir

    # Convenience pointer to the most recent run for this target.
    ^ln -sfn $dir ($runs | path join $"latest-($target)")

    # Keep only the 5 newest runs per target. Timestamped dirs start with a
    # digit (so this never matches the latest-* symlink) and sort
    # chronologically by name; sort+reverse puts the newest first.
    glob $"($runs)/[0-9]*-($target)-*"
    | sort
    | reverse
    | skip 5
    | each { |old| rm -rf $old }

    $dir
}

# Caddyfile for isolated integration tests:
# - listen :0 (no clash with a local dev server on :8080)
# - admin on a per-run unix socket (so `caddy stop` hits this instance only)
# - no identity header rewrite (isolation.hurl sets X-Token-Subject per request;
#   todos.hurl gets identity via hurl --header)
#
# Returns the admin address string for start/stop (`unix//abs/path.sock`).
export def write-test-caddyfile [dir: string]: nothing -> string {
    let sock = ($dir | path join admin.sock)
    # Absolute path → `unix//home/.../admin.sock` (network + absolute path).
    let admin = $"unix/($sock)"

    # Plain string (not $"…"): parentheses in pragma values must not be
    # treated as Nu command interpolation.
    let body = "# Generated by mise test — do not edit.
{
	admin __ADMIN__
}

:0 {
	route {
		xtemplate {
			controller watchfs {
				path templates
			}

			provider sql DB {
				driver sqlite3
				connstr file:./todos.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=foreign_keys(1)
			}
			provider bus Bus {
				buffer 32
			}
		}
	}
}
"
    $body | str replace "__ADMIN__" $admin | save --force ($dir | path join Caddyfile)

    $admin
}

# Wait for a server to accept requests on /. curl retries through the brief
# startup window, where connection errors are expected; capture curl's output
# and surface it only if the probe ultimately fails, so those transient retry
# messages don't clutter the log.
export def wait-ready [port: int, retries: int = 10] {
    let probe = (^curl -fsS --retry $retries --retry-all-errors --retry-connrefused --retry-delay 1 $"http://localhost:($port)/" | complete)
    if $probe.exit_code != 0 {
        print -e $probe.stderr
        error make --unspanned { msg: $"readiness probe for port ($port) failed" }
    }
}

# Wait for a server started on an ephemeral port (`:0`) to log its chosen
# address, then return the port it bound, so integration tests never collide
# with whatever else happens to be running on the host. Matches both xtemplate's
# slog output (`...address=[::]:PORT`) and Caddy's JSON (`"actual_address":
# "[::]:PORT"`).
export def wait-listen-port [log: string] {
    for _ in 1..50 {
        if ($log | path exists) {
            let m = (open --raw $log | parse --regex '(?:actual_address":"|address=)[^" \n]*:(?<port>[0-9]+)')
            if not ($m | is-empty) { return ($m | last | get port | into int) }
        }
        sleep 100ms
    }
    error make --unspanned { msg: $"server did not report a listen address in ($log)" }
}

# Run the hurl suite against a running server. The .hurl files hardcode
# localhost:8080, so --connect-to remaps that to the target's actual port.
#
# todos.hurl expects a fixed "dev" identity (same as the local Caddyfile).
# isolation.hurl sets X-Token-Subject per request — requires a server that does
# NOT rewrite those headers (see write-test-caddyfile).
export def run-hurl [port: int, report: string] {
    wait-ready $port 10
    mkdir $report
    let connect = $"localhost:8080:localhost:($port)"
    mut failed = []

    let todos_dir = ($report | path join todos)
    mkdir $todos_dir
    let todos = (
        ^hurl --continue-on-error --no-output --test --report-html $todos_dir
            --connect-to $connect
            --header "X-Token-Subject: dev"
            --header "X-Token-User-Name: Local Dev"
            ($env.ROOT | path join tests/todos.hurl)
        | complete
    )
    if $todos.exit_code != 0 {
        print $todos.stdout
        print -e $todos.stderr
        $failed = ($failed | append "todos.hurl")
    }

    let iso_dir = ($report | path join isolation)
    mkdir $iso_dir
    let iso = (
        ^hurl --continue-on-error --no-output --test --report-html $iso_dir
            --connect-to $connect
            ($env.ROOT | path join tests/isolation.hurl)
        | complete
    )
    if $iso.exit_code != 0 {
        print $iso.stdout
        print -e $iso.stderr
        $failed = ($failed | append "isolation.hurl")
    }

    if not ($failed | is-empty) {
        error make --unspanned { msg: $"hurl failed: ($failed | str join ', ')" }
    }
}

# Stop the Caddy started for a test run. Prefer admin via the generated
# Caddyfile; fall back to the pidfile if the admin API is unreachable.
export def stop-test-caddy [caddy: string, work: string] {
    let stop = (do { cd $work; ^$caddy stop --config Caddyfile } | complete)
    if $stop.exit_code == 0 { return }

    let pidfile = ($work | path join caddy.pid)
    if not ($pidfile | path exists) {
        print -e $"caddy stop failed and no pidfile: ($stop.stderr)"
        return
    }
    let pid = (open --raw $pidfile | str trim)
    print -e $"caddy stop failed; killing pid ($pid)"
    try { ^kill $pid } catch { }
    sleep 200ms
    try { ^kill -9 $pid } catch { }
}
